### ISSUE TITLE
Display Problem

### ISSUE THREAD

**Issue by Potterd** [UsrLightmann/StripeCount#5] opened 2021-05-06 20:32 UTC
Sometimes works and sometimes looks like the attached screenshot - force close Zebra and reopen seems to fix
![687296F9-17CE-4F9A-88AA-4F2FDD304DBA](https://user-images.githubusercontent.com/2848810/117361899-73a92580-ae6f-11eb-9f01-31013878899e.png)

**Comment by Potterd** [comment] 2021-05-06 22:54
Last occurrence - force close Zebra and reopen did not fix, reinstall StripeCount to fix

**Comment by Potterd** [comment] 2021-05-06 22:55
Sorry, didn’t mean to close

**Comment by Potterd** [comment] 2021-05-08 17:00
Lately, reinstall Zebra to fix - there is no reliable workaround to fix this, all of the steps mentioned can work or not work to return the display to normal

**Comment by L1ghtmann** [comment] 2021-05-08 20:22
What version of StripeCount are you using? The reason I'm asking is because this width issue was addressed back in v1.0.3.1. 

Also, what device, iOS version, and Zebra version?

**Comment by Potterd** [comment] 2021-05-08 21:16
Thanks for getting back to me !

 

StripeCount v1.0.3.2.2

iPhone 8

iOS 14.3

Zebra v1.1.18

 

Also was able to reproduce with Zebra v1.1.17

 

Let me know if you need anything additional.

 

Regards,

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 ***@***.***> ***@***.***

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting

**Comment by Potterd** [comment] 2021-05-14 21:53
Hope you are still looking at this / Plz let me know if you need anything additional / help with testing .....

**Comment by Potterd** [comment] 2021-05-17 03:59
2nd device iPhone SE either the same issue: 
![574EBBFE-387E-4021-A1ED-0713F28E318A](https://user-images.githubusercontent.com/2848810/118430721-3856f400-b6c4-11eb-9bd0-961248af733b.png)

**Comment by Potterd** [comment] 2021-05-17 03:59
2nd device with the same issue .....

**Comment by Potterd** [comment] 2021-05-24 17:54
Any update ?
Have you been able to reproduce this issue or should I be testing for a tweak conflict.

**Comment by L1ghtmann** [comment] 2021-05-29 21:51
I have not been able to replicate this, no. Could you shoot me an email (lightmanns11@gmail.com)?

**Comment by Potterd** [comment] 2021-05-29 23:05
Hope you received my earlier messages .....

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
***@***.***

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by UsrLightmann** [comment] 2021-06-06 06:46
Hey, any word on the build I sent over? I still have a couple ideas I could try out if the issue isn't resolved.

**Comment by L1ghtmann** [comment] 2021-06-08 20:44
Thanks again for your help testing! 

Fixed in v1.0.3.3.

**Closed as completed by L1ghtmann** 2021-06-08 20:44 UTC
